### ISSUE TITLE
下载的时候失败

### ISSUE THREAD

**Issue by joe21244966** [renyunkang/yuque-exporter#1]
Error: Download timed out
    at Timeout._onTimeout (file:///D:/git_project/yuque-exporter/main.js:256:16)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Download error: Error: Download timed out

**Comment by renyunkang** [comment]
> Error: Download timed out at Timeout._onTimeout (file:///D:/git_project/yuque-exporter/main.js:256:16) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7) Download error: Error: Download timed out

刚刚测试过没有问题，请检查自己配置的环境变量是否有问题，或者提供其他更多的信息(如：文件名称，电脑磁盘大小是否被占满等)，方便排查

**Comment by williamyang2008** [comment]
我也是出现download timeout的错误，提示如下：Error: Download timed out
at Timeout._onTimeout (file:///C:/Users/Administrator/main.js:256:16)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
