### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by jadeyansir** [renyunkang/yuque-exporter#11]
大佬一直报错是怎么回事呀
Login use user + password...
file:///E:/AIproject/yuque-exporter/node_modules/puppeteer-core/lib/esm/puppeteer/common/LifecycleWatcher.js:158
    return new TimeoutError(errorMessage);
           ^

TimeoutError: Navigation timeout of 30000 ms exceeded
    at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (file:///E:/AIproject/yuque-exporter/node_modules/puppeteer-core/lib/esm/puppeteer/common/LifecycleWatcher.js:
158:12)
    at async Frame.waitForNavigation (file:///E:/AIproject/yuque-exporter/node_modules/puppeteer-core/lib/esm/puppeteer/common/Frame.js:252:23)
    at async CDPPage.waitForNavigation (file:///E:/AIproject/yuque-exporter/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:445:16)
    at async autoLogin (file:///E:/AIproject/yuque-exporter/src/login.js:45:7)
    at async run (file:///E:/AIproject/yuque-exporter/main.js:44:5)

E:\AIproject\yuque-exporter>

**Comment by renyunkang** [comment]
1. 检查是否使用的是最新的代码，语雀的登录界面更新了滑动验证
2. 修改 https://github.com/renyunkang/yuque-exporter/blob/master/main.js#L40C58-L40C58 为 headless: false 观察在运行时卡在哪一步了

**Comment by jadeyansir** [comment]
感谢大佬，解决了，是因为""的问题

**Comment by jadeyansir** [comment]
有些文档出现这种超时错误，为什么呢
Error: Download timed out
    at Timeout._onTimeout (file:///E:/AIproject/yuque-exporter/src/export.js:123:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by renyunkang** [comment]
看下文档的文档名称是否有特殊字符呢

**Comment by jadeyansir** [comment]
是有特殊字符，这种类型文档还挺多，需要怎么处理呢

**Comment by renyunkang** [comment]
- 可以修改文档名称
- 可以在 https://github.com/renyunkang/yuque-exporter/blob/master/src/toc.js#L172C10-L172C24 添加没有处理的特殊字符，替换为下划线 _

**Comment by faith2god** [comment]
```
Waiting download document to files\运维开发学习记录\笔试面试\面试经验
Error: Download timed out
    at Timeout._onTimeout (file:///C:/Users/fuyuanyuan/Downloads/yuque-exporter-master/src/export.js:123:20)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Retrying download... (attempt 3)
```

下载超时怎么回事啊
