### ISSUE TITLE
卡在登录这步，一直超时

### ISSUE THREAD

**Issue by mobyoung** [renyunkang/yuque-exporter#4]
windows环境执行node main.js 这步总是返回超时错误。
不知道是什么原因。
我这用户名是手机号码，是不是手机号码要加86之类的？
Login use user + password...
file:///C:/Windows/System32/yuque-exporter/node_modules/puppeteer-core/lib/esm/puppeteer/common/LifecycleWatcher.js:158
    return new TimeoutError(errorMessage);
           ^

TimeoutError: Navigation timeout of 30000 ms exceeded
    at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (file:///C:/Windows/System32/yuque-exporter/node_modules/puppeteer-core/lib/esm/puppeteer/common/LifecycleWatcher.js:158:12)
    at async Frame.waitForNavigation (file:///C:/Windows/System32/yuque-exporter/node_modules/puppeteer-core/lib/esm/puppeteer/common/Frame.js:252:23)
    at async CDPPage.waitForNavigation (file:///C:/Windows/System32/yuque-exporter/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:445:16)
    at async file:///C:/Windows/System32/yuque-exporter/main.js:84:5

**Comment by renyunkang** [comment]
不用加86，应该是你的账号密码不对，检查检查

**Comment by mobyoung** [comment]
set ACCESSURL是填写https://www.yuque.com/XXX吗？

**Comment by renyunkang** [comment]
写 xxx 就行

**Comment by mobyoung** [comment]
账号密码确实是对的，accessurl也改了，还是不行，不知道是否和前些天语雀出问题有关系。

**Comment by rookieuncle** [comment]
账号密码对也下载不了了，我这可以下载下来两三个页面，剩下的都是超时，10s改到100s也不行，应该是被识别了

**Comment by renyunkang** [comment]
取消掉这一行的注释，重新运行看看日志，可能是文件中的特殊字符没有处理到 https://github.com/renyunkang/yuque-exporter/blob/daf4ef82e769a5f8aa66142c6ba58e08d742e737/src/export.js#L109

```
             console.log(`watch ${rootPath} ${eventType} ${filename}, want ${mdname}.md`)
```

**Comment by rookieuncle** [comment]
> 取消掉这一行的注释，重新运行看看日志，可能是文件中的特殊字符没有处理到
> 
> https://github.com/renyunkang/yuque-exporter/blob/daf4ef82e769a5f8aa66142c6ba58e08d742e737/src/export.js#L109
> 
> ```
>              console.log(`watch ${rootPath} ${eventType} ${filename}, want ${mdname}.md`)
> ```

sorry，昨晚上在windows上执行报错，今天在mac可以了

不过仍有两个点需要注意：
 1. excel不支持导出
 2. 注意语雀文档文件名，后边可能有空格，也不能导出，在本地是  `xxx .md` 而不是 `xxx.md`, 前者是不行的

**Comment by renyunkang** [comment]
> sorry，昨晚上在windows上执行报错，今天在mac可以了
> 
> 不过仍有两个点需要注意：
> 
> 1. excel不支持导出
> 2. 注意语雀文档文件名，后边可能有空格，也不能导出，在本地是  `xxx .md` 而不是 `xxx.md`, 前者是不行的

感谢指出问题，另外说明一下：

- 纯 excel 和 纯 思维导图是不支持导出，这个官方也没有直接导出为 mardown 的支持，需要自己手动导出为表格或者其他格式的文件

**Comment by mobyoung** [comment]
最后装了Ubuntu的虚拟机成功下载了。

**Comment by Scr1pt-kid** [comment]
powershell成功了
